Repository rajatkb/Conference-Notify, pull requests merged in 2020-05, with the labels that each got.

#95 Fixed broken links in Readme.md
  README.md
Labels: beginner, gssoc20

#83 Adding Travis Continuous Integration
  .travis.yml
  Scrapper-Service/requirements.txt
  User-App/src/app/app.component.spec.ts
  User-App/src/app/home/home.component.spec.ts
Labels: enhancement, gssoc20, medium

#93 Update ReadMe of Scrapper_Service
  Scrapper-Service/README.md
Labels: beginner, documentation, gssoc20

#98 Added login page UI
  User-App/src/app/app.module.ts
  User-App/src/app/login/login.component.css
  User-App/src/app/login/login.component.html
  User-App/src/app/login/login.component.ts
Labels: easy, gssoc20

#81 Social Media profiles of Project handlers
  README.md
Labels: easy, good first issue, gssoc20

#90 Frontend: Add conferences list and View Conference Page
  Notifier-service/.env
  Notifier-service/src/app.ts
  User-App/src/app/app-routing.module.ts
  User-App/src/app/app.module.ts
  User-App/src/app/conference/conference.component.css
  User-App/src/app/conference/conference.component.html
  User-App/src/app/conference/conference.component.spec.ts
  User-App/src/app/conference/conference.component.ts
  User-App/src/app/conferences-list/conferences-list.component.css
  User-App/src/app/conferences-list/conferences-list.component.html
  User-App/src/app/conferences-list/conferences-list.component.spec.ts
  User-App/src/app/conferences-list/conferences-list.component.ts
  User-App/src/app/home/home.component.html
  User-App/src/app/models/conference.model.ts
  User-App/src/app/models/conferenceDocument.model.ts
  User-App/src/app/models/metadata.model.ts
  User-App/src/app/services/conferences.service.spec.ts
  User-App/src/app/services/conferences.service.ts
  package-lock.json
Labels: gssoc20, medium
