Repository rajatkb/Conference-Notify, pull requests merged in 2020-03, with the labels that each got.

#14 Basic User-App Structure Added
  User-App/.editorconfig
  User-App/.gitignore
  User-App/README.md
  User-App/angular.json
  User-App/browserslist
  User-App/e2e/protractor.conf.js
  User-App/e2e/src/app.e2e-spec.ts
  User-App/e2e/src/app.po.ts
  User-App/e2e/tsconfig.json
  User-App/karma.conf.js
  User-App/package-lock.json
  User-App/package.json
  User-App/src/app/app-routing.module.ts
  User-App/src/app/app.component.css
  User-App/src/app/app.component.html
  User-App/src/app/app.component.spec.ts
  User-App/src/app/app.component.ts
  User-App/src/app/app.module.ts
  User-App/src/app/header/header.component.css
  User-App/src/app/header/header.component.html
  User-App/src/app/header/header.component.spec.ts
  User-App/src/app/header/header.component.ts
  User-App/src/app/home/home.component.css
  User-App/src/app/home/home.component.html
  User-App/src/app/home/home.component.spec.ts
  User-App/src/app/home/home.component.ts
  User-App/src/app/login/login.component.css
  User-App/src/app/login/login.component.html
  User-App/src/app/login/login.component.spec.ts
  User-App/src/app/login/login.component.ts
  User-App/src/app/signup/signup.component.css
  User-App/src/app/signup/signup.component.html
  User-App/src/app/signup/signup.component.spec.ts
  User-App/src/app/signup/signup.component.ts
  User-App/src/assets/.gitkeep
  User-App/src/environments/environment.prod.ts
  User-App/src/environments/environment.ts
  User-App/src/favicon.ico
  User-App/src/index.html
  User-App/src/main.ts
  User-App/src/polyfills.ts
  User-App/src/styles.css
  User-App/src/test.ts
  User-App/tsconfig.app.json
  User-App/tsconfig.json
  User-App/tsconfig.spec.json
  User-App/tslint.json
Labels: easy, gssoc20

#21 Contribution Guideline Updated
  CONTRIBUTING.md
Labels: beginner, documentation, gssoc20

#19 [Improve] change _id parameter for Conference model
  Scrapper-Service/commons/__pycache__/__init__.cpython-36.pyc
  Scrapper-Service/commons/__pycache__/database.cpython-36.pyc
  Scrapper-Service/commons/__pycache__/errors.cpython-36.pyc
  Scrapper-Service/commons/__pycache__/scrapper.cpython-36.pyc
  Scrapper-Service/database/__pycache__/__init__.cpython-36.pyc
  Scrapper-Service/database/__pycache__/db.cpython-36.pyc
  Scrapper-Service/database/__pycache__/mdb.cpython-36.pyc
  Scrapper-Service/datamodels/__pycache__/__init__.cpython-36.pyc
  Scrapper-Service/datamodels/__pycache__/conference.cpython-36.pyc
  Scrapper-Service/datamodels/__pycache__/metadata.cpython-36.pyc
  Scrapper-Service/datamodels/conference.py
  Scrapper-Service/plugins/__pycache__/__init__.cpython-36.pyc
  Scrapper-Service/plugins/__pycache__/demo.cpython-36.pyc
  Scrapper-Service/plugins/__pycache__/wikicfp.cpython-36.pyc
  Scrapper-Service/utility/__pycache__/__init__.cpython-36.pyc
  Scrapper-Service/utility/__pycache__/argument.cpython-36.pyc
  Scrapper-Service/utility/__pycache__/logger.cpython-36.pyc
Labels: enhancement, gssoc20, medium

#23 Tests for metadata datamodel added
  README.md
  Scrapper-Service/test_metadata.py
Labels: enhancement, gssoc20, medium

#35 [scrapper] add requirements.txt
  Scrapper-Service/requirements.txt
Labels: beginner, documentation, gssoc20

#31 fix(app.py): Spell fix for couple of variables
  Scrapper-Service/app.py
Labels: beginner, enhancement, gssoc20

#32 Create readme.md for the design mockup folder.
  Design Mockups/Confrence_Notify_v2.png
  Design Mockups/Design Mockups/Assets/Proj_Conf_ntfy_logo-01.png
  Design Mockups/Design Mockups/Assets/Proj_Conf_ntfy_logo-01.svg
  Design Mockups/Design Mockups/Assets/Proj_Conf_ntfy_logo.ai
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017.png
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017@2x.png
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017_c.png
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017_c@2x.png
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017_cz.png
  Design Mockups/Design Mockups/Assets/Ref_Google_Maps_25_10_2017_cz@2x.png
  Design Mockups/Design Mockups/Assets/crowded_people_standing_watchi.png
  Design Mockups/Design Mockups/Assets/crowded_people_standing_watchi@2x.png
  Design Mockups/Design Mockups/Assets/man_standing_in_front_of_peopl.png
  Design Mockups/Design Mockups/Assets/man_standing_in_front_of_peopl@2x.png
  Design Mockups/Design Mockups/Assets/people_gathering_inside_white_.png
  Design Mockups/Design Mockups/Assets/people_gathering_inside_white_@2x.png
  Design Mockups/Design Mockups/Code for refernce/Confrence_Notify_v2.html
  Design Mockups/readme.md
Labels: easy, enhancement, gssoc20

#50 Removed pkg-resources from requirements.txt
  Scrapper-Service/requirements.txt
Labels: beginner, documentation, gssoc20

#58 All missing model functions added
  Notifier-service/src/models/conference.ts
Labels: enhancement, gssoc20, medium

#55 Added ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/pull_request.md
Labels: documentation, easy, gssoc20

#61 [documentation] modify main.py to app.py in README
  README.md
Labels: beginner, documentation, enhancement

#62 Environment variable check added
  Notifier-service/package-lock.json
  Notifier-service/package.json
  Notifier-service/src/server.ts
  Search-Service/package-lock.json
  Search-Service/package.json
  Search-Service/src/server.ts
Labels: easy, enhancement, gssoc20

#63 Added service functions
  Notifier-service/src/services/conference.ts
Labels: easy, enhancement, gssoc20

#25 Home page Design Implemented
  User-App/package-lock.json
  User-App/package.json
  User-App/src/app/app-routing.module.ts
  User-App/src/app/app.module.ts
  User-App/src/app/header/header.component.css
  User-App/src/app/header/header.component.html
  User-App/src/app/home/home.component.css
  User-App/src/app/home/home.component.html
  User-App/src/app/home/home.component.ts
  User-App/src/app/search-page/search-page.component.css
  User-App/src/app/search-page/search-page.component.html
  User-App/src/app/search-page/search-page.component.spec.ts
  User-App/src/app/search-page/search-page.component.ts
  User-App/src/assets/Proj_Conf_ntfy_logo-01.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017@2x.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017_c.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017_c@2x.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017_cz.png
  User-App/src/assets/Ref_Google_Maps_25_10_2017_cz@2x.png
  User-App/src/assets/crowded_people_standing_watchi.png
  User-App/src/assets/crowded_people_standing_watchi@2x.png
  User-App/src/assets/man_standing_in_front_of_peopl.png
  User-App/src/assets/man_standing_in_front_of_peopl@2x.png
  User-App/src/assets/people_gathering_inside_white_.png
  User-App/src/assets/people_gathering_inside_white_@2x.png
Labels: gssoc20, medium

#69 [scrapper utility] add redirect functionality to adaptive_request
  Scrapper-Service/commons/scrapper.py
  Scrapper-Service/utility/adapative_request.py
Labels: easy, enhancement, gssoc20
