Repository rajatkb/Conference-Notify, pull requests merged in 2020-04, with the labels that each got.

#75 Close Function and event listener added
  Notifier-service/src/app.ts
  Notifier-service/src/database/mongodb.ts
  Notifier-service/src/interfaces/database.ts
  Notifier-service/src/inversify.config.ts
Labels: easy, enhancement, gssoc20

#43 [Scrapper-Service]add g2r scrapper, modify config.json
  Scrapper-Service/config.json
  Scrapper-Service/plugins/guide2research.py
  Scrapper-Service/requirements.txt
Labels: enhancement, gssoc20, hard

#79 Added pull request template
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: beginner, enhancement, good first issue, gssoc20

#77 Update Prerequisites in README.md
  README.md
Labels: beginner, documentation, gssoc20

#74 Added cors package
  Notifier-service/.env
  Notifier-service/package-lock.json
  Notifier-service/package.json
  Notifier-service/src/app.ts
Labels: beginner, enhancement, good first issue, gssoc20

#89 Modified_array_push_to_store_unique_categories
  Scrapper-Service/datamodels/conference.py
Labels: bug, easy, gssoc20

#84 Fixing Github templates
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: beginner, documentation, good first issue, gssoc20

#71 [documentation] added instructions to run scraper service in different modes
  Scrapper-Service/README.md
Labels: beginner, documentation, gssoc20

#51 insert to mongo db on having greater datestamp for deadline, trigger a rest call for same
  Scrapper-Service/database/mdb.py
  Scrapper-Service/test/__init__.py
  Scrapper-Service/test/mongodb_test.py
Labels: enhancement, gssoc20, medium

#92 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: beginner, documentation, gssoc20

#82 Added CRUD streams
  Notifier-service/src/app.ts
  Notifier-service/src/interfaces/services/streams/conferenceStream.ts
  Notifier-service/src/interfaces/stream.ts
  Notifier-service/src/services/streams/conferenceStream.ts
Labels: enhancement, gssoc20, medium
